/**
 * Skill reference generator — emits the Agent Skill's reference files from the
 * same registries the site renders, so the skill can never drift from what
 * accessible-by-default.dev actually shows.
 *
 * SKILL.md itself is hand-written (it holds the decisions); only the files
 * under skills/accessible-by-default/references/ are generated. Run after
 * changing either registry.
 *
 * Only context-free fields are emitted. The registries' `summary`, `passText`
 * and `failText` are written for someone looking at a live demo ("use the
 * slider", "six tab stops here"), so the criteria reference uses `requirement`
 * alone, and the CSS catalog takes only the first sentence of each summary —
 * the part that states what the feature is rather than what the demo does.
 *
 * The registries import .vue components and ?raw snippets, so they are loaded
 * through Vite's SSR pipeline rather than plain node.
 *
 * Run:  npm run skill:gen
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

import { createServer } from 'vite'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const refs = resolve(root, 'skills/accessible-by-default/references')

const SITE = 'https://accessible-by-default.dev'

const TIERS = [
  ['widely-available', 'Baseline: widely available', 'Safe to ship unguarded.'],
  [
    'newly-available',
    'Baseline: newly available',
    'Interoperable across current engines, but older installs are still out there. Guard it, and give the fallback a real path.',
  ],
  [
    'limited-availability',
    'Limited availability',
    'Not interoperable yet. Progressive enhancement only — the page must be complete without it.',
  ],
]

const banner = (title, from) =>
  `<!-- Generated by scripts/gen-skill.mjs from ${from}. Do not edit by hand. -->\n\n# ${title}\n\n`

/** What the feature is, minus any instruction aimed at the live demo. */
const firstSentence = (text) => {
  const match = text.match(/^[\s\S]*?[.!?](?=\s|$)/)
  return (match ? match[0] : text).trim()
}

const guardOf = (s) =>
  s.supports
    ? `\`@supports (${s.supports})\``
    : s.detect
      ? 'Feature-detect in JS — no CSS condition expresses it.'
      : 'No guard needed.'

const linkList = (links) => (links ?? []).map((l) => `- [${l.label}](${l.href})`).join('\n')

const server = await createServer({
  server: { middlewareMode: true },
  appType: 'custom',
  logLevel: 'error',
})

const { criteria } = await server.ssrLoadModule('/src/criteria/registry.ts')
const { showcases } = await server.ssrLoadModule('/src/showcases/registry.ts')
await server.close()

// --- WCAG criteria --------------------------------------------------------
const criteriaDoc =
  banner('WCAG success criteria the platform can satisfy natively', 'src/criteria/registry.ts') +
  'Each entry states the requirement and who pays when it is missed. These are\n' +
  'the criteria most often broken by hand-built components that a native element\n' +
  `would have satisfied for free. Interactive versions: ${SITE}/standard.html\n\n` +
  criteria
    .map((c) =>
      [
        `## ${c.id} ${c.name}`,
        `**Level ${c.level} · ${c.version} · ${c.principle}**`,
        c.requirement,
        linkList(c.links),
      ]
        .filter(Boolean)
        .join('\n\n'),
    )
    .join('\n\n') +
  '\n'

// --- Catalog: what to reach for, and whether it is safe yet ---------------
const catalogDoc =
  banner('Modern CSS and HTML, by how safe it is to ship', 'src/showcases/registry.ts') +
  'Tiers come from the `web-features` Baseline dataset at build time, not from\n' +
  'anyone’s opinion. Accessible implementations of every entry below are in\n' +
  `\`css-snippets.md\`. Live versions: ${SITE}/showcase.html\n\n` +
  TIERS.map(([tier, heading, advice]) => {
    const group = showcases.filter((s) => s.tier === tier)
    if (!group.length) return ''
    const body = group
      .map((s) =>
        [
          `### ${s.title}`,
          firstSentence(s.summary),
          `**Accessibility payoff:** ${s.payoff}`,
          `**Guard:** ${guardOf(s)}`,
          s.tags?.length ? `**Topics:** ${s.tags.join(', ')}` : '',
          linkList(s.links),
        ]
          .filter(Boolean)
          .join('\n\n'),
      )
      .join('\n\n')
    return [`## ${heading}`, advice, body].join('\n\n')
  })
    .filter(Boolean)
    .join('\n\n') +
  '\n'

// --- Snippets: the accessible form of each feature ------------------------
const withCode = showcases.filter((s) => s.snippetHtml || s.snippetCss || s.snippetJs)
const snippetsDoc =
  banner('Accessible implementations, feature by feature', 'src/showcases/registry.ts') +
  'Every excerpt keeps semantics, honours user preferences, and degrades to\n' +
  'something usable. They are free of this project’s tokens and mixins, so they\n' +
  'are copy-paste ready. Never copy one without the guard named beneath it —\n' +
  `check its tier in \`modern-css.md\` first.\n\n` +
  withCode
    .map((s) =>
      [
        `## ${s.title}`,
        `**Guard:** ${guardOf(s)}`,
        s.snippetHtml && '```html\n' + s.snippetHtml.trim() + '\n```',
        s.snippetCss && '```css\n' + s.snippetCss.trim() + '\n```',
        s.snippetJs && '```js\n' + s.snippetJs.trim() + '\n```',
      ]
        .filter(Boolean)
        .join('\n\n'),
    )
    .join('\n\n') +
  '\n'

mkdirSync(refs, { recursive: true })
for (const [name, doc, count] of [
  ['wcag-criteria.md', criteriaDoc, `${criteria.length} criteria`],
  ['modern-css.md', catalogDoc, `${showcases.length} features`],
  ['css-snippets.md', snippetsDoc, `${withCode.length} implementations`],
]) {
  writeFileSync(resolve(refs, name), doc)
  console.log(`✓ ${name} (${count})`)
}
